Serializable trees
domenicquirl/cstree pull request #11
Opened 2021-01-16 11:05 UTC by Stupremee

Make `SyntaxNode` serializable by implementing `Serialize` and `Deserialize`.

A serialized tree is basically a list of events (`EnterNode`, `LeaveNode`, `Token`),
which are then used in conjunction with a `GreenNodeBuilder` to build up a new tree
that looks the same as the serialized one.

Resolves #4

2021-01-19 00:00 UTC, domenicquirl requested changes
Thank you very much for your persistent work on this! ☺️ 
I've left a few detail reviews as comments for final polish, after that this should be ready to go (and hopefully that should also mean that I can get CI going, which would be great)

2021-01-19 13:50 UTC, Stupremee commented on tests/serde.rs
> +fn serialize_data_tree_without_data() {
Yea the tests need some cleanup.

2021-01-19 13:50 UTC, Stupremee commented on tests/serde.rs
> +fn serialize_data_tree_without_data() {
Yea the tests need some cleanup.

2021-01-19 13:51 UTC, Stupremee commented on tests/common.rs
> +#![allow(unused)]
This was just for keeping my console clean :sweat_smile:

2021-01-19 14:53 UTC, domenicquirl commented on tests/common.rs
> +#![allow(unused)]
To avoid misunderstandings, I do like the code to not emit warnings. But the solution for that should be to either address the individual warnings or `#[allow]` specific parts where really needed ^^

2021-01-19 15:20 UTC, Stupremee commented on tests/common.rs
> +#![allow(unused)]
yes of course

2021-01-25 09:44 UTC, domenicquirl requested changes
We're definitely almost done! Everything runs fine for me. It may seem like a lot of comments again, but basically all of that is minor docs/naming issues, you did a great job on the actual implementations! ☺️ 
I'm very interesting on your opinion on leftover data after deserializing the tree (see comment). What do you think is the right thing to do there?

2021-01-25 09:44 UTC, domenicquirl commented on src/serde_impls.rs
> +/// The macro will not use the `$counter` if the data list is not given.
`$counter` is now gone since we switched to the boolean representation, so this probably needs to go

2021-01-25 09:44 UTC, domenicquirl commented on src/serde_impls.rs
> +/// data that is serializable.
This comment seems to still be for the "without data" case? Should be something along the lines of "include data in serialization" I think

2021-01-25 09:44 UTC, domenicquirl commented on src/serde_impls.rs
> +                let tree = SyntaxNode::new_root_with_resolver(tree, resolver.unwrap());
If we always deserialize into trees with inline resolver (which I think is fine for now), then we should `into_resolver` the interner (`resolver`) here. Seems unlikely that users will then try to get the interner out and re-use it, especially if their other deserialized trees can't then use that. See https://docs.rs/lasso/0.4.1/lasso/trait.Reader.html#tymethod.into_resolver, should be quick and easy

2021-01-25 09:44 UTC, domenicquirl commented on src/serde_impls.rs
> +
Should we check that `data` is empty at this point, so there is not serialized data left that wasn't used? I don't know what good practice is for that, since technically we were able to create a tree

2021-01-25 09:44 UTC, domenicquirl commented on src/syntax.rs
> +        D: serde::Serialize,
We don't need this bound, do we? I think tests work because the default for `D` is `()`, which implements `Deserialize`, but we shouldn't require that

2021-01-25 09:44 UTC, domenicquirl commented on tests/serde.rs
> +    let tree = SyntaxNode::<String, ()>::new_root(root.clone());
Because of the comment on `as_serialize_with_resolver`, can you make this tree have non-`Deserialize` data?

2021-01-25 09:44 UTC, domenicquirl commented on tests/serde.rs
> +fn serialize_tree_with_resolver_with_data() {
Can this be the same way round as the original `SyntaxNode` method?

2021-01-27 08:08 UTC, Stupremee commented on src/serde_impls.rs
> +
Yea I think that makes sense so the user can catch the errors faster than figuring out what's missing

2021-01-27 10:44 UTC, merged